name: Unit tests check

on:
  # Scan changed files in PRs (diff-aware scanning):
  # The branches below must be a subset of the branches above
  pull_request:
    branches: ["master", "main"]
  push:
    branches: ["master", "main"]

jobs:
  test:
    runs-on: macos-latest-xl

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test
